"""add memories table

Revision ID: dd1d98bc24b0
Revises: 0003
Create Date: 2026-09-25 15:37:10.751975
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'dd1d98bc24b0'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('ws_id', sa.String(length=26), nullable=False),
    sa.Column('persona_id', sa.String(length=26), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('thread_id', sa.String(length=26), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ws_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_persona_id'), 'memories', ['persona_id'], unique=False)
    op.create_index(op.f('ix_memories_ws_id'), 'memories', ['ws_id'], unique=False)
    op.create_index('ix_memories_ws_kind', 'memories', ['ws_id', 'kind', 'created_at'], unique=False)
    # NOTE: autogenerate also detected pre-existing schema drift unrelated to this migration
    # (ix_events_undispatched, personas->workspaces FK, users email unique constraint) — left
    # untouched here; that drift predates this change and should be handled separately.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memories_ws_kind', table_name='memories')
    op.drop_index(op.f('ix_memories_ws_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_persona_id'), table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
