#!/bin/bash
# deploy-site.sh — provision one Site's container: create its Postgres database,
# build+start the site-template image, register it with HAProxy/NGINX so its
# subdomain is actually reachable, then report back once it's live.
#
# Counterpart to deploy-worker.sh, for the Sites feature (PLAN.md "Sites" section)
# rather than the pooled agent-worker pool. Key difference from deploy-worker.sh:
# a Site is a per-tenant, one-off container built from a git checkout that ships
# WITH this repo (site-template/ — see site-template/README.md), not a shared
# pre-built image, and it needs its own database + a reachable HTTP subdomain,
# neither of which a worker needs (workers have no inbound HTTP at all).
#
# Called from the Jenkins job (jenkins.site_provision_job, db_settings.py) with
# the mainforte repo already checked out into the current directory (standard
# Jenkins workspace behavior) — same as deploy-worker.sh.
#
# Params (Jenkins job) — must match what sites/provisioning.py's trigger_provision
# actually sends via trigger_jenkins_build:
#   SITE_ID             — the Site row's id (mainforte's own, opaque to this script
#                          beyond being a label/log line and the callback path)
#   SUBDOMAIN           — the site's slug, e.g. "babysitting-biz" — used to derive
#                          CONTAINER_NAME and as deploy-light.sh's --slug/--subdomain
#   CONTAINER_API_KEY   — plaintext capability token the container sends back as
#                          `Authorization: Bearer` on every callback (site-template's
#                          lib/callback.ts, verified in routes.py's site_callback)
#   CALLBACK_URL        — mainforte's own POST /api/sites/{id}/callback endpoint
#   TEMPLATE            — which starter template to use. Only "default" exists today
#                          (site-template/ in this repo); the param is accepted and
#                          recorded so a future multi-template catalog doesn't need a
#                          job-contract change, but any other value is currently an error.
#   DB_NAME, DB_USER, DB_PASSWORD       — this site's own Postgres role + database,
#                          generated by provisioning.py (never by this script). NOTE:
#                          deploy-light.sh has its own --provision-db flag, but it
#                          derives DB_NAME/DB_USER from --slug alone and mints its own
#                          random password — incompatible with mainforte's own
#                          deterministic "site_{slug}" naming and pre-generated
#                          DB_PASSWORD (provisioning.py never persists the plaintext,
#                          so there's nothing for deploy-light.sh to look up either).
#                          So DB bootstrap stays a separate, explicit step here via
#                          bootstrap-db.sh directly, same as before — --provision-db
#                          is intentionally not used.
#   DB_ADMIN_USER, DB_ADMIN_PASSWORD    — admin Postgres credential used to run
#                          bootstrap-db.sh; forwarded from db_settings.py's db.admin_*
#                          Settings. Also forwarded to deploy-light.sh itself (as
#                          POSTGRES_ADMIN_USER/POSTGRES_ADMIN_PASS below), since it
#                          hard-requires its own connection to the shared "backbone"
#                          state database to register anything, independent of this
#                          site's own per-site database.
#
# Env this script expects to already be present on the Jenkins/deploy host (never
# passed in by the caller, never typed into chat — same convention as
# deploy-worker.sh's own env-var block):
#   DB_HOST, DB_PORT     — the shared Postgres cluster's host/port this site's own
#                          database lives on (defaults below match what
#                          bootstrap-db.sh/deploy-light.sh resolve to on this infra)
#   SITES_PARENT_DOMAIN  — defaults to mainforte.ai; forwarded into the container as
#                          PARENT_DOMAIN (see site-template's email.ts reset-link logic)
#                          and used to build deploy-light.sh's --aliases
#   SESSION_SECRET_SALT  — a host-side secret used to derive this container's
#                          SESSION_SECRET deterministically from SITE_ID (so a
#                          container restart on the same host doesn't invalidate
#                          every session) — falls back to a per-run random secret
#                          (logged nowhere) if unset, meaning sessions won't survive
#                          a redeploy until this is configured. Never typed into chat.
#
# HAProxy/NGINX routing: handled by /etc/backbone/scripts/deploy-light.sh (backbone's
# own "register an already-running container" script — see its own usage()/header for
# the full contract). This is the real, already-existing mechanism used elsewhere on
# this infra; earlier drafts of this script deferred subdomain routing as separate
# not-yet-designed work, but sites/service.py already promises a real
# https://{slug}.mainforte.ai/ published_url, so this step is not optional.
set -euo pipefail

: "${SITE_ID:?SITE_ID is required}"
: "${SUBDOMAIN:?SUBDOMAIN is required}"
: "${CONTAINER_API_KEY:?CONTAINER_API_KEY is required}"
: "${CALLBACK_URL:?CALLBACK_URL is required}"
: "${DB_NAME:?DB_NAME is required}"
: "${DB_USER:?DB_USER is required}"
: "${DB_PASSWORD:?DB_PASSWORD is required}"
TEMPLATE="${TEMPLATE:-default}"
DB_ADMIN_USER="${DB_ADMIN_USER:-}"
DB_ADMIN_PASSWORD="${DB_ADMIN_PASSWORD:-}"

if [ "$TEMPLATE" != "default" ]; then
    echo "ERROR: unknown TEMPLATE '$TEMPLATE' — only 'default' (site-template/) exists today." >&2
    exit 1
fi

CONTAINER_NAME="site-${SUBDOMAIN}"
DB_HOST="${DB_HOST:-db.activeaidemo.com}"
DB_PORT="${DB_PORT:-5432}"
SITES_PARENT_DOMAIN="${SITES_PARENT_DOMAIN:-mainforte.ai}"
DEPLOY_LIGHT_SH="/etc/backbone/scripts/deploy-light.sh"
BOOTSTRAP_DB_SH="/etc/backbone/scripts/bootstrap-db.sh"

echo "Deploying site: $SITE_ID (subdomain=$SUBDOMAIN, container=$CONTAINER_NAME)"

# --- 1. Database: idempotent role+database create/update, same script every other
#     app on this cluster already uses (PLAN.md "Per-site Postgres provisioning") ---
echo "  Bootstrapping database $DB_NAME (user=$DB_USER) on ${DB_HOST}:${DB_PORT}..."
BOOTSTRAP_ARGS=(-d "$DB_NAME" -u "$DB_USER" -p "$DB_PASSWORD" -H "$DB_HOST" -P "$DB_PORT" --app-slug "$CONTAINER_NAME")
if [ -n "$DB_ADMIN_USER" ]; then
    BOOTSTRAP_ARGS+=(-A "$DB_ADMIN_USER")
fi
if [ -n "$DB_ADMIN_PASSWORD" ]; then
    BOOTSTRAP_ARGS+=(-W "$DB_ADMIN_PASSWORD")
fi
"$BOOTSTRAP_DB_SH" "${BOOTSTRAP_ARGS[@]}"

DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

# --- 2. Build the template image ---
# site-template/ ships in this same repo checkout (Jenkins already has it via the
# standard workspace checkout) — no separate clone step needed, unlike beactive-claw's
# per-tenant-repo model. See site-template/README.md's "How a site boots".
SITE_TEMPLATE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/site-template"
IMAGE_TAG="site-template:${SITE_ID}"
echo "  Building image $IMAGE_TAG from $SITE_TEMPLATE_DIR..."
docker build -t "$IMAGE_TAG" "$SITE_TEMPLATE_DIR"

# --- 3. Stop/remove any previous container for this site (redeploy case) ---
echo "  Stopping/removing any existing container named $CONTAINER_NAME..."
docker stop "$CONTAINER_NAME" >/dev/null 2>&1 || true
docker rm "$CONTAINER_NAME" >/dev/null 2>&1 || true

# Deterministic per-site session secret so a redeploy on the same host doesn't log
# every existing session out — see the SESSION_SECRET_SALT env-var comment above.
if [ -n "${SESSION_SECRET_SALT:-}" ]; then
    SESSION_SECRET="$(printf '%s' "${SESSION_SECRET_SALT}:${SITE_ID}" | sha256sum | cut -d' ' -f1)"
else
    echo "  WARNING: SESSION_SECRET_SALT not set on this host — using a one-off random secret;"
    echo "           existing sessions will NOT survive a future redeploy of this site."
    SESSION_SECRET="$(head -c32 /dev/urandom | sha256sum | cut -d' ' -f1)"
fi

# --- 4. Start it. Docker itself picks a free host port so this script never needs
#     its own port-allocation bookkeeping — `docker port` reads back whatever it
#     chose, and that's the port handed to deploy-light.sh below. Bound to all
#     interfaces (not loopback-only): deploy-light.sh/HAProxy needs to reach it, and
#     HAProxy itself is the actual public-facing boundary — same trust model as
#     every other container-behind-HAProxy app on this infra.
echo "  Starting..."
docker run -d \
    --name "$CONTAINER_NAME" \
    --restart unless-stopped \
    -p 3000 \
    -e "NODE_ENV=production" \
    -e "PORT=3000" \
    -e "DATABASE_URL=$DATABASE_URL" \
    -e "SITE_ID=$SITE_ID" \
    -e "SUBDOMAIN=$SUBDOMAIN" \
    -e "PARENT_DOMAIN=$SITES_PARENT_DOMAIN" \
    -e "CALLBACK_URL=$CALLBACK_URL" \
    -e "CONTAINER_API_KEY=$CONTAINER_API_KEY" \
    -e "SESSION_SECRET=$SESSION_SECRET" \
    "$IMAGE_TAG"

DEV_PORT="$(docker port "$CONTAINER_NAME" 3000/tcp | head -n1 | cut -d: -f2)"
if [ -z "$DEV_PORT" ]; then
    echo "ERROR: could not read back the host port Docker assigned to $CONTAINER_NAME" >&2
    exit 1
fi
echo "  Started on host port $DEV_PORT."

# --- 5. Register with HAProxy/NGINX so {SUBDOMAIN}.mainforte.ai actually routes to
#     this container's port. This is the real, already-existing mechanism other apps
#     on this infra use (deploy-light.sh's own header: "thin peer of deploy-site.sh
#     ... register an already-running container with HAProxy + NGINX"). Preview is
#     served from mainforte's own /sites/preview/{token}/ proxy route (routes.py),
#     not this subdomain — this registration is what makes the *published* URL
#     (sites/service.py's published_url: https://{slug}.mainforte.ai/) real.
#     --allow-iframe: mainforte's own in-app preview iframes this container directly
#     via the preview proxy path, and the published site may itself be iframed by
#     the user's own marketing pages — same posture as beactive-claw's sample.
echo "  Registering with HAProxy/NGINX via deploy-light.sh..."
"$DEPLOY_LIGHT_SH" \
    --slug "$CONTAINER_NAME" \
    --port "$DEV_PORT" \
    --subdomain "$SUBDOMAIN" \
    --domain "${SUBDOMAIN}.${SITES_PARENT_DOMAIN}" \
    --container "$CONTAINER_NAME" \
    --health-endpoint "/api/health" \
    --allow-iframe \
    --cors-origins "*.${SITES_PARENT_DOMAIN}"

# --- 6. Authoritative "ready" callback — this job step, not the in-container startup
#     ping, is the one place that knows CONTAINER_NAME/DEV_PORT (see PLAN.md's "Site
#     starter template fork" > "Replace the control plane"). The container's own
#     lib/callback.ts already sent a lighter "app process is up" ping; this is the
#     callback mark_ready() actually needs.
echo "  Reporting ready to $CALLBACK_URL..."
curl -sS --fail-with-body -X POST "$CALLBACK_URL" \
    -H "Authorization: Bearer $CONTAINER_API_KEY" \
    -H "Content-Type: application/json" \
    -d "$(printf '{"event":"ready","container_name":"%s","dev_port":%s}' "$CONTAINER_NAME" "$DEV_PORT")"

echo "  Done. Site $SITE_ID is live at container=$CONTAINER_NAME port=$DEV_PORT, https://${SUBDOMAIN}.${SITES_PARENT_DOMAIN}/"
