"""S3-backed master copy of a site's source tree, plus the per-turn local scratch checkout the
persona's file tools actually read/write against — PLAN.md's Sites section, "Live editing:
revised design" (supersedes the original one-`docker exec`-per-write design).

The running container's filesystem is a disposable, resyncable *view* of the S3 master, not the
source of truth. Per turn: pull the current master into a local scratch dir (`pull_master`),
let the persona's tool calls edit that scratch copy directly (plain local filesystem I/O — see
`tools/catalog.py`'s `_read_site_file`/`_write_site_file`/`_list_site_files`), then at turn end
`commit_turn` validates, ships to the container via `docker cp`, confirms the process came back
up, and — only if all of that succeeded — pushes the scratch dir back to S3 as the new master and
bumps `Site.source_version`. A failure at any step leaves the previous S3 master and the running
container both untouched, so a bad turn never corrupts the durable copy.

Mirrors homes.py's tar.zst manifest+blob pattern exactly (same `get_storage()`, same shelling out
to `tar --zstd` via storage.py's `tar_dir`/`untar_bytes` — promoted there from homes.py's own
private copies since this is the second real call site). Key scheme is `sites/{site_id}/...`,
per-site rather than per-user — see storage.py's `site_source_key`/`site_source_latest_key` and
PLAN.md's note on why this isn't workspace/group-scoped.

`node_modules` is deliberately excluded from every tar — installed once in the container at
provision time (the template's Dockerfile `npm install` layer) and not part of the per-turn sync.
See `_EXCLUDE` and PLAN.md's note on this.
"""
from __future__ import annotations

import json
import logging
import shutil
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from mainforte.storage import get_storage, site_source_key, site_source_latest_key, tar_dir, untar_bytes

log = logging.getLogger(__name__)

# Never synced through S3/docker cp each turn — see module docstring. `.git`/`dist`/`build` are
# also excluded: `dist`/`build` are regenerated by the validate step (see ship_to_container),
# shipping stale build output would be actively wrong, and `.git` has no reason to exist in a
# site's working tree at all today (the template isn't cloned with history into the container).
_EXCLUDE = ("node_modules", ".git", "dist", "build")

SCRATCH_ROOT = Path("/tmp/sites")


class SourceError(RuntimeError):
    pass


@dataclass
class TurnScratch:
    site_id: str
    version: int  # the version this scratch was pulled from — not yet incremented
    path: Path  # local scratch checkout root


def _scratch_path(site_id: str, correlation_id: str) -> Path:
    # Keyed by correlation_id (one per chat turn, per router.py) rather than just site_id, so two
    # concurrent turns on the same site (shouldn't normally happen, but a retried/duplicate
    # dispatch is possible) never share — and silently corrupt — one scratch dir.
    return SCRATCH_ROOT / site_id / correlation_id


def pull_master(site_id: str, correlation_id: str) -> TurnScratch:
    """Downloads the current S3 master (or starts from an empty tree if this site has no master
    yet — shouldn't happen post-provisioning, but don't hard-fail a first edit racing the
    turn-0 seed) into a fresh local scratch dir for this turn. Idempotent-ish: re-pulling for the
    same correlation_id wipes and redoes the scratch dir, since a stale partial scratch from a
    crashed prior attempt at the same turn should never be reused silently."""
    storage = get_storage()
    dest = _scratch_path(site_id, correlation_id)
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True, exist_ok=True)

    raw = storage.get(site_source_latest_key(site_id))
    if raw is None:
        log.warning("site %s has no S3 source master yet — starting turn %s from an empty tree",
                    site_id, correlation_id)
        return TurnScratch(site_id=site_id, version=0, path=dest)

    latest = json.loads(raw)
    version = int(latest["version"])
    data = storage.get(site_source_key(site_id, version))
    if data is None:
        raise SourceError(f"site {site_id} latest.json names version {version} but that tarball is missing")
    untar_bytes(data, dest)
    return TurnScratch(site_id=site_id, version=version, path=dest)


def validate_scratch(scratch: TurnScratch) -> str | None:
    """Runs the same build the container itself needs (`node build.mjs`, run from
    artifacts/api-server/ — see site-template/dev.sh's `cd "$API_DIR" && node ./build.mjs`, NOT the
    scratch root) against the scratch checkout. Returns None on success, or the raw technical error
    text on failure (caller decides what to do with it — see catalog.py/router.py: this is never
    shown to the user as-is). Skips cleanly (returns None) if the scratch tree doesn't have this
    file yet (e.g. an empty first-pull before turn-0 seeding ever completed, or a template layout
    that hasn't been forked yet) — nothing to validate in that case, not a failure."""
    api_dir = scratch.path / "artifacts" / "api-server"
    build_script = api_dir / "build.mjs"
    if not build_script.is_file():
        return None
    result = subprocess.run(
        ["node", "build.mjs"], cwd=api_dir, capture_output=True, text=True, timeout=180,
    )
    if result.returncode != 0:
        return (result.stderr or result.stdout or "build failed")[-4000:]
    return None


def ship_to_container(db, site, scratch: TurnScratch) -> str | None:
    """`docker cp`s the validated scratch dir into the site's container and confirms the process
    came back up cleanly. Returns None on success, or the raw technical error (never shown as-is
    to the user) on failure. Caller (commit_turn) must not push to S3 or bump source_version if
    this returns an error — the container and the S3 master must never diverge from what was
    actually validated."""
    from mainforte.sites.container_agent import ContainerAgentError, docker_cp_in, tail_logs_for_errors

    try:
        docker_cp_in(db, site, scratch.path, exclude=_EXCLUDE)
    except ContainerAgentError as e:
        return str(e)
    return tail_logs_for_errors(db, site)


def commit_turn(site_id: str, correlation_id: str, scratch: TurnScratch) -> int:
    """Pushes the scratch dir back to S3 as the new master and returns the new version number.
    Only call this after `ship_to_container` returned None (success) — this function itself does
    not re-validate, it just persists what the caller already confirmed is good. Caller is
    responsible for bumping `Site.source_version` in the DB to the returned value."""
    storage = get_storage()
    new_version = scratch.version + 1
    data = tar_dir(scratch.path, exclude=_EXCLUDE)
    storage.put(site_source_key(site_id, new_version), data, "application/zstd")
    now = datetime.now(timezone.utc)
    import hashlib

    latest = {
        "version": new_version,
        "sha256": hashlib.sha256(data).hexdigest(),
        "updated_at": now.isoformat(),
    }
    storage.put(site_source_latest_key(site_id), json.dumps(latest).encode(), "application/json")
    return new_version


def discard_scratch(site_id: str, correlation_id: str) -> None:
    """Cleans up the local scratch dir without touching S3 or the container — the turn's edits
    (if any landed on disk) simply vanish, same as if the turn had never happened. Called when a
    turn's edits never get to a successful ship_to_container (e.g. the roundtrip budget ran out
    mid-retry) so scratch dirs don't accumulate under SCRATCH_ROOT indefinitely."""
    dest = _scratch_path(site_id, correlation_id)
    if dest.exists():
        shutil.rmtree(dest, ignore_errors=True)


def seed_turn_zero(site_id: str, template_dir: Path) -> int:
    """Called once at site-creation time (from provisioning.trigger_provision, before the Jenkins
    job fires) to capture the site-template tree — as it ships in this mainforte checkout — into
    S3 as the turn-0 master. Returns the version written (always 0). This is the same tree the
    Jenkins job's own `docker build` uses; capturing it here too means the very first chat edit
    has a real S3 master to pull from rather than a special-cased "no master yet" path."""
    storage = get_storage()
    data = tar_dir(template_dir, exclude=_EXCLUDE)
    storage.put(site_source_key(site_id, 0), data, "application/zstd")
    import hashlib

    latest = {
        "version": 0,
        "sha256": hashlib.sha256(data).hexdigest(),
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    storage.put(site_source_latest_key(site_id), json.dumps(latest).encode(), "application/json")
    return 0
